name: Deploy Airflow to EC2

on:
  workflow_run:
    workflows: ["Provision Infrastructure"]  # Trigger after the first workflow completes
    types:
      - completed
    status: success

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Retrieve EC2 Public IP from S3
        run: |
          aws s3 cp s3://samkons-reddit-dataengineering/ec2_public_ip.txt ec2_public_ip.txt
          export EC2_PUBLIC_IP=$(cat ec2_public_ip.txt)
          echo "EC2_PUBLIC_IP=${EC2_PUBLIC_IP}" >> $GITHUB_ENV

      - name: Debug EC2 Public IP
        run: |
          echo "EC2_PUBLIC_IP from GITHUB_ENV: ${{ env.EC2_PUBLIC_IP }}"

      - name: Ensure Required Directories Exist
        run: |
          mkdir -p logs dags data config plugins tests
          echo "Directories created or already exist"


      - name: Check Files for SCP
        run: |
          echo "Checking files for SCP..."
          ls -l ./docker-compose.yml
          ls -l ./config/ || echo "Config directory not found"

      - name: Upload docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ env.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ./docker-compose.yml
          target: /home/ubuntu/airflow/

      - name: Upload Application Files to EC2
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ env.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ./config ./dags ./data ./etls ./logs ./pipelines ./plugins ./tests ./utils ./glue_job ./requirements.txt
          target: /home/ubuntu/airflow/  # Target directory on EC2

      - name: SSH to EC2 and Deploy Airflow
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ env.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Pulling Airflow Docker image"
            docker pull samkons/samkons-custom-airflow:latest

            echo "Navigating to the directory"
            cd /home/ubuntu/airflow/

            echo "Running docker-compose"
            docker-compose up -d
