name: Deploy Airflow to EC2

on:
  workflow_run:
    workflows: ["Provision Infrastructure"]  # Trigger after the first workflow completes
    types:
      - completed
    status: success

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Retrieve EC2 Public IP from S3
        run: |
          aws s3 cp s3://samkons-reddit-dataengineering/ec2_public_ip.txt ec2_public_ip.txt
          export EC2_PUBLIC_IP=$(cat ec2_public_ip.txt)
          echo "EC2_PUBLIC_IP=${EC2_PUBLIC_IP}" >> $GITHUB_ENV

      - name: Debug EC2 Public IP
        run: |
          echo "EC2_PUBLIC_IP from GITHUB_ENV: ${{ env.EC2_PUBLIC_IP }}"

      - name: Add EC2 Host Key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ env.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts


      - name: Decode SSH Private Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem



      - name: Debug SSH Private Key
        run: |
          echo "Length of EC2_SSH_KEY: ${#EC2_SSH_KEY}"

      - name: Check ec2_key.pem
        run: |
          ls -l ec2_key.pem
          cat ec2_key.pem

      - name: Test SSH Connection
        run: |
          ssh -i ec2_key.pem ubuntu@${{ env.EC2_PUBLIC_IP }} "echo 'Connection successful'"


      - name: Debug GitHub Workspace and SCP Key Path
        run: |
          echo "GitHub Workspace: ${{ github.workspace }}"
          ls -l ${{ github.workspace }}/ec2_key.pem

      - name: Ensure correct permissions on ec2_key.pem
        run: |
          chmod 600 ${{ github.workspace }}/ec2_key.pem
          ls -l ${{ github.workspace }}/ec2_key.pem 

      - name: Upload docker-compose.yml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml, config, dags,  etls, logs, pipelines, utils, glue_job, requirements.txt"
          target: /home/ubuntu/airflow/
          debug: true

      - name: SSH to EC2 and set up
        run: |
          ssh -i ec2_key.pem ubuntu@${{ env.EC2_PUBLIC_IP }} << EOF
          #!/bin/bash
          sudo apt update -y
          sudo apt-get install -y python3-pip curl jq
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          
          # Add user to Docker group (so you don't need sudo to run docker)
          sudo usermod -aG docker ubuntu
          
          newgrp docker
          
          # Install Docker Compose
          sudo apt-get install -y curl
          sudo curl -L "https://github.com/docker/compose/releases/download/\$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-\$(uname -s)-\$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          
          # Verify Docker and Docker Compose installation
          docker --version
          docker-compose --version
         
          echo "Creating airflow.env with secrets"
          cat <<EOT > /home/ubuntu/airflow/airflow.env
          AIRFLOW__CORE__EXECUTOR=CeleryExecutor
          AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
          AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://postgres:postgres@postgres:5432/airflow_reddit
          AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@postgres:5432/airflow_reddit
          AIRFLOW__CORE__FERNET_KEY=${{ secrets.AIRFLOW_CORE_FERNET_KEY }}
          AIRFLOW__CORE__LOGGING_LEVEL=INFO
          AIRFLOW__CORE__LOAD_EXAMPLES=False
          AIRFLOW_ADMIN_USERNAME=${{ secrets.AIRFLOW_ADMIN_USERNAME }}
          AIRFLOW_ADMIN_EMAIL=${{ secrets.AIRFLOW_ADMIN_EMAIL }}
          AIRFLOW_ADMIN_PASSWORD=${{ secrets.AIRFLOW_ADMIN_PASSWORD }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          EOT
          echo "airflow.env file created"
        
          echo "Pulling Airflow Docker image"
          docker pull samkons/samkons-custom-airflow:latest
      
          echo "Navigating to the Airflow directory"
          cd /home/ubuntu/airflow
      
          echo "Running Docker Compose"
          docker-compose up -d
          EOF
