name: Provision Infrastructure

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Output EC2 Public IP
        run: |
          EC2_PUBLIC_IP=$(terraform output -raw ec2_public_ip)
          echo "EC2 Public IP is $EC2_PUBLIC_IP"
          echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV  
